### ISSUE TITLE
Git platform independence [feature request]

### ISSUE THREAD

**Issue by a223y** [iotaledger/ict#38]
Getting ixi installed by web-gui from any .git, not just github.

**Comment by mikrohash** [comment]
Support could be extended to all platforms which use the same API structure as GitHub.

**Comment by mikrohash** [comment]
Closing because adding support for other platforms is a lot of work due to API differences. For now GitHub should suffice. In the final version, it should of course support all major platforms. However, for the current Ict prototype, development should focus more on general protocol concepts and less on convenience (UX and platform support).
