### ISSUE TITLE
Neighbor graph bug

### ISSUE THREAD

**Issue by svenger87** [iotaledger/ict#47]
There is a bug when you switch to the neighbor page after a fresh login.
The graph for transactions spikes down to 0 for the next round.

Pretty minor thing tbh. But might be a bit confusing.

![image](https://user-images.githubusercontent.com/35897839/53801957-decdd900-3f40-11e9-9005-4dc24ba9ae77.png)

**Comment by lambtho12** [comment]
I might be wrong, but I think it is because the stats are "real-time". So if you log in the beginning of the last epoch, it will be almost zero. If you log at the end of the epoch it will be "normal". Then if you refresh, that last datapoint will increase gradually. 

Try refreshing a few times quickly to see it.

That being said, it is true that it might be a bit confusing. A solution could be to plot only the completed epoch.

**Comment by svenger87** [comment]
Hmm that makes sense. 

Maybe only the last epoch should be loaded at initial view of the graph.
